{% set name = "hpp-environments" %}
{% set version = "6.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6045b0711f5b55480d4e32f3b104d25bc262d4b1a4f0f3c6a239baa97bc6536a

build:
  number: 0
  skip: true  # [win or python_impl == 'pypy']
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - hpp-fcl                                # [build_platform != target_platform]
    - pinocchio                              # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - libboost-headers
    - python
    - example-robot-data
    - hpp-fcl
    - pinocchio
  run:
    - python
    - example-robot-data

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
